### ISSUE TITLE
Dragging instantly removes the gap being dragged from

### ISSUE THREAD

**Issue by hortont424** [jmvx/skyrim-followers#1]
When you go to drag people around, upon starting the drag, the space which you are dragging from immediately collapses, and you're dragging on top of the next person over. It seems like it would be better if the gap remained until the drop occurs, or perhaps at least until the mouse is no longer over the gap.

**Comment by jmvx** [comment]
Fixed in d16505baab4634ec626646e97d667a1a02479acd
